export { Header } from "./Header";
export { Footer } from "./Footer";
export { HeroPage } from "./HeroPage";
export { SearchBox } from "./SearchBox";
export { OfferCarousel } from "./OfferCarousel";
export { SpecializationPage } from "./SpecializationPage";
export { SpecialistPage } from "./SpecialistPage";
export { CaringPage } from "./CaringPage";
export { NewsSection } from "./NewsSection";
export { OurFamiliesSection } from "./OurFamiliesSection";
export {QuerySection} from "./QuerySection";
export { AppLinkSection } from "./AppLinkSection";
export{MyBookingSearchSection} from "./MyBookingSearchSection";
